name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          user: Kenway23
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
